title: User Guides
baseurl: "/ex-user-guides" # the subpath of your site, e.g. /blog

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

color_scheme: csun
theme: "just-the-docs"